/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ateliejunino.telas;

import com.mycompany.ateliejunino.TelaBase;
import com.mycompany.ateliejunino.daos.AluguelDao;
import com.mycompany.ateliejunino.entidades.Aluguel;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CadastroAluguel extends TelaBase {

    /**
     * Creates new form ReservadoTraje
     */
    public CadastroAluguel() {
       aluguelDao = new AluguelDao();
         initComponents();
        setLocationRelativeTo(null);
        carregarAtendentesComboBox();
    }
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    

 private AluguelDao aluguelDao;
 
    private void carregarAtendentesComboBox() {
    List<String> atendentes = aluguelDao.listarAtendentes();
    for (String nome : atendentes) {
        comboAtendente.addItem(nome);
    }
}

private String getSelecaoButtonGroup() {
    if (Lacos.isSelected()) {
        return "Laços";
    } else if (Anagua.isSelected()) {
        return "Anágua";
    } else if (Chapeu.isSelected()) {
        return "Chapéu";
    } else if (Veu.isSelected()) {
        return "Véu";
    } else if (Buque.isSelected()) {
        return "Buquê";
    }
    return null; // Nenhuma opção selecionada
}
private void salvarSelecaoEmArquivo() {
    String selecao = getSelecaoButtonGroup(); // Obtém a opção selecionada
    
    // Verifica se alguma opção foi selecionada
    if (selecao == null) {
        JOptionPane.showMessageDialog(this, "Nenhuma opção selecionada!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try (FileWriter writer = new FileWriter("selecao.txt", true)) { // 'true' para adicionar ao invés de sobrescrever
        writer.write(selecao + "\n"); // Adiciona a seleção no arquivo com quebra de linha
        JOptionPane.showMessageDialog(this, "Seleção salva com sucesso!");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Erro ao salvar a seleção!", "Erro", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NumTrajeL = new javax.swing.JLabel();
        DataRF = new javax.swing.JTextField();
        DataQF = new javax.swing.JTextField();
        HorarioF = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        DataD = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        ValorTotal = new javax.swing.JLabel();
        VoltarB = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        SalvarB = new javax.swing.JButton();
        ValorF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        AdiantamentoF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        RestanteF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Lacos = new javax.swing.JRadioButton();
        Anagua = new javax.swing.JRadioButton();
        Buque = new javax.swing.JRadioButton();
        Veu = new javax.swing.JRadioButton();
        Chapeu = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ObsF = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        NumTrajeF = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        comboAtendente = new javax.swing.JComboBox<>();
        NumTrajeL1 = new javax.swing.JLabel();
        EscolaF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NumTrajeL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NumTrajeL.setText("Número do Traje:");

        DataRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataRFActionPerformed(evt);
            }
        });

        DataQF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataQFActionPerformed(evt);
            }
        });

        HorarioF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorarioFActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("Hórario:");

        DataD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataDActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Data da Quadrilha:");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("Data da Devolução:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("Data da Reserva:");

        ValorTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ValorTotal.setText("Valor do Traje:");

        VoltarB.setText("Voltar");
        VoltarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Adiantamento:");

        SalvarB.setText("Salvar");
        SalvarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarBActionPerformed(evt);
            }
        });

        ValorF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorFActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("R$");

        AdiantamentoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdiantamentoFActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("R$");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Restante:");

        RestanteF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestanteFActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("R$");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setText("Acompanhamentos:");

        Lacos.setText("Laços\n");
        Lacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LacosActionPerformed(evt);
            }
        });

        Anagua.setText("Anágua");
        Anagua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnaguaActionPerformed(evt);
            }
        });

        Buque.setText("Buquê");
        Buque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuqueActionPerformed(evt);
            }
        });

        Veu.setText("Véu\n");
        Veu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeuActionPerformed(evt);
            }
        });

        Chapeu.setText("Chápeu");
        Chapeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChapeuActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setText("Observação:");

        ObsF.setColumns(20);
        ObsF.setRows(5);
        jScrollPane1.setViewportView(ObsF);

        jLabel1.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Reserva do Traje");

        NumTrajeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumTrajeFActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("Atendente:");

        comboAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAtendenteActionPerformed(evt);
            }
        });

        NumTrajeL1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NumTrajeL1.setText("Escola:");

        EscolaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscolaFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(AdiantamentoF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(230, 230, 230))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel24)
                                            .addGap(88, 88, 88))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel30)
                                            .addGap(31, 31, 31)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Lacos)
                                            .addGap(18, 18, 18)
                                            .addComponent(Anagua))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(18, 18, 18)
                                            .addComponent(RestanteF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(ValorTotal)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(NumTrajeL)
                                            .addGap(78, 78, 78)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ValorF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NumTrajeF, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buque)
                        .addGap(18, 18, 18)
                        .addComponent(Veu)
                        .addGap(18, 18, 18)
                        .addComponent(Chapeu))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel29)
                                .addComponent(jLabel28)
                                .addComponent(jLabel26))
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(DataQF, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(HorarioF, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DataRF)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel27)
                                .addComponent(jLabel32))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboAtendente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DataD)))
                        .addComponent(NumTrajeL1))
                    .addComponent(EscolaF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(VoltarB)
                        .addGap(45, 45, 45)
                        .addComponent(SalvarB)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumTrajeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumTrajeL))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ValorTotal)
                            .addComponent(ValorF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AdiantamentoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RestanteF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(DataQF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(HorarioF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(DataRF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(DataD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Lacos)
                        .addComponent(Anagua)
                        .addComponent(Buque)
                        .addComponent(Veu)
                        .addComponent(Chapeu)
                        .addComponent(jLabel32)
                        .addComponent(comboAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EscolaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NumTrajeL1)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VoltarB)
                    .addComponent(SalvarB))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DataRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataRFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataRFActionPerformed

    private void DataQFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataQFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataQFActionPerformed

    private void HorarioFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorarioFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HorarioFActionPerformed

    private void DataDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataDActionPerformed

    private void VoltarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBActionPerformed
        Menu menu = new Menu(); // Criar uma nova instância da tela Menu
        menu.setVisible(true); // Tornar o Menu visível
        this.dispose();
    }//GEN-LAST:event_VoltarBActionPerformed

    private void SalvarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarBActionPerformed
    try {
    if (NumTrajeF.getText().isEmpty() || ValorF.getText().isEmpty() || AdiantamentoF.getText().isEmpty() ||
        RestanteF.getText().isEmpty() || DataQF.getText().isEmpty() || HorarioF.getText().isEmpty() || DataD.getText().isEmpty()) { 
        
        JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
LocalDate dataQuadrilha = LocalDate.parse(DataQF.getText(), formatter);
LocalDate dataReserva = LocalDate.parse(DataRF.getText(), formatter);
LocalDate dataDevolucao = LocalDate.parse(DataD.getText(), formatter);

    Aluguel aluguel = new Aluguel();

    aluguel.setNumeroTraje(Integer.parseInt(NumTrajeF.getText()));
    aluguel.setValor(Double.parseDouble(ValorF.getText()));
    aluguel.setAdiantamento(Double.parseDouble(AdiantamentoF.getText()));
    aluguel.setRestante(Double.parseDouble(RestanteF.getText()));

    aluguel.setDataQuadrilha(LocalDate.parse(DataQF.getText(), formatter));
    aluguel.setDataReserva(LocalDate.parse(DataRF.getText(), formatter));
    aluguel.setDataDevolucao(LocalDate.parse(DataD.getText(), formatter));

    aluguel.setObservacao(ObsF.getText());
    aluguel.setAcompanhamentos(getSelecaoButtonGroup());

    String atendenteSelecionado = (String) comboAtendente.getSelectedItem();
    aluguel.setAtendente(atendenteSelecionado);

    aluguel.setEscola(EscolaF.getText());

    aluguelDao.salvar(aluguel);
    JOptionPane.showMessageDialog(this, "Aluguel cadastrado com sucesso!");
    salvarSelecaoEmArquivo();
    this.dispose();
         Menu menu = new Menu(); // Criar uma nova instância da tela Menu
        menu.setVisible(true);

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Erro nos valores numéricos!", "Erro", JOptionPane.ERROR_MESSAGE);
} catch (DateTimeParseException e) {
    JOptionPane.showMessageDialog(this, "Formato de data inválido. Use o formato dd/MM/yyyy.", "Erro", JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Erro ao salvar o aluguel: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
}

    }//GEN-LAST:event_SalvarBActionPerformed

    private void ValorFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorFActionPerformed

    private void AdiantamentoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdiantamentoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdiantamentoFActionPerformed

    private void RestanteFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestanteFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RestanteFActionPerformed

    private void LacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LacosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LacosActionPerformed

    private void AnaguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnaguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnaguaActionPerformed

    private void BuqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuqueActionPerformed

    private void VeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VeuActionPerformed

    private void ChapeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChapeuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChapeuActionPerformed

    private void NumTrajeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumTrajeFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumTrajeFActionPerformed

    private void comboAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAtendenteActionPerformed

    private void EscolaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscolaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscolaFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAluguel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdiantamentoF;
    private javax.swing.JRadioButton Anagua;
    private javax.swing.JRadioButton Buque;
    private javax.swing.JRadioButton Chapeu;
    private javax.swing.JTextField DataD;
    private javax.swing.JTextField DataQF;
    private javax.swing.JTextField DataRF;
    private javax.swing.JTextField EscolaF;
    private javax.swing.JTextField HorarioF;
    private javax.swing.JRadioButton Lacos;
    private javax.swing.JTextField NumTrajeF;
    private javax.swing.JLabel NumTrajeL;
    private javax.swing.JLabel NumTrajeL1;
    private javax.swing.JTextArea ObsF;
    private javax.swing.JTextField RestanteF;
    private javax.swing.JButton SalvarB;
    private javax.swing.JTextField ValorF;
    private javax.swing.JLabel ValorTotal;
    private javax.swing.JRadioButton Veu;
    private javax.swing.JButton VoltarB;
    private javax.swing.JComboBox<String> comboAtendente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
