/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ateliejunino.telas;

import com.mycompany.ateliejunino.TelaBase;
import com.mycompany.ateliejunino.daos.TrajeDao;
import com.mycompany.ateliejunino.entidades.Traje;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author User
 */
public class EditarTraje extends TelaBase {

    /**
     * Creates new form EditarTraje
     */
    public EditarTraje(int trajeId) {
    this.trajeId = this.trajeId;

        trajeDao = new TrajeDao();

        initComponents();

        setLocationRelativeTo(null);
    }
 private int trajeId;
    private TrajeDao trajeDao;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        VoltarB = new javax.swing.JButton();
        NumTrajeL = new javax.swing.JLabel();
        SalvarB = new javax.swing.JButton();
        NumTrajeF = new javax.swing.JTextField();
        ValorTotal = new javax.swing.JLabel();
        ValorF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescTrajeF = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Edição Cadastro do Traje");

        VoltarB.setText("Voltar");
        VoltarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBActionPerformed(evt);
            }
        });

        NumTrajeL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NumTrajeL.setText("Número do Traje:");

        SalvarB.setText("Salvar");
        SalvarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    SalvarBActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        NumTrajeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumTrajeFActionPerformed(evt);
            }
        });

        ValorTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ValorTotal.setText("Valor do Traje:");

        ValorF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorFActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("R$");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setText("Descrição do Traje:");

        DescTrajeF.setColumns(20);
        DescTrajeF.setRows(5);
        jScrollPane1.setViewportView(DescTrajeF);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VoltarB)
                .addGap(54, 54, 54)
                .addComponent(SalvarB)
                .addGap(428, 428, 428))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ValorTotal)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2))
                    .addComponent(NumTrajeL)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValorF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumTrajeF, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumTrajeL)
                    .addComponent(NumTrajeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValorTotal)
                    .addComponent(ValorF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VoltarB)
                    .addComponent(SalvarB))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBActionPerformed
        Menu menu = new Menu(); // Criar uma nova instância da tela Menu
        menu.setVisible(true); // Tornar o Menu visível
        this.dispose();
    }//GEN-LAST:event_VoltarBActionPerformed

    private void SalvarBActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_SalvarBActionPerformed
      
    // Validação dos campos obrigatórios
    if (NumTrajeF.getText().isEmpty() || ValorF.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Conversão dos valores dos campos
        int numeroTraje = Integer.parseInt(NumTrajeF.getText());
        double valor = Double.parseDouble(ValorF.getText());
        String descricao = DescTrajeF.getText();

        // Criação do objeto Traje
        Traje traje = new Traje(numeroTraje, valor, descricao);

        // Salvamento do traje
        trajeDao.salvar(traje);

        // Mensagem de sucesso
        JOptionPane.showMessageDialog(this, "Traje cadastrado com sucesso!");
        this.dispose();
         Menu menu = new Menu(); // Criar uma nova instância da tela Menu
        menu.setVisible(true);
    } catch (NumberFormatException e) {
        // Tratamento de erro de conversão numérica
        JOptionPane.showMessageDialog(this, "Erro nos valores numéricos!", "Erro", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        // Tratamento de outras exceções
        JOptionPane.showMessageDialog(this, "Erro ao salvar o traje: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }         // TODO add your handling code here:
    }//GEN-LAST:event_SalvarBActionPerformed

    private void NumTrajeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumTrajeFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumTrajeFActionPerformed

    private void ValorFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorFActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarTraje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarTraje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarTraje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarTraje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarTraje(trajeId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DescTrajeF;
    private javax.swing.JTextField NumTrajeF;
    private javax.swing.JLabel NumTrajeL;
    private javax.swing.JButton SalvarB;
    private javax.swing.JTextField ValorF;
    private javax.swing.JLabel ValorTotal;
    private javax.swing.JButton VoltarB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
