/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ateliejunino.telas;

import com.mycompany.ateliejunino.TelaBase;
import com.mycompany.ateliejunino.daos.AluguelDao;
import com.mycompany.ateliejunino.entidades.Aluguel;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class EditarAluguel extends TelaBase {


    EditarAluguel(int aluguelId) {
    initComponents();
     this.aluguelId = this.aluguelId;

        aluguelDao = new AluguelDao();

        initComponents();

        setLocationRelativeTo(null);
    }  
    private int aluguelId;
    private AluguelDao aluguelDao;
    
private String getSelecaoButtonGroup() {
    if (Lacos.isSelected()) {
        return "Laços";
    } else if (Anagua.isSelected()) {
        return "Anágua";
    } else if (Chapeu.isSelected()) {
        return "Chapéu";
    } else if (Veu.isSelected()) {
        return "Véu";
    } else if (Buque.isSelected()) {
        return "Buquê";
    }
    return null; // Nenhuma opção selecionada
}
private void salvarSelecaoEmArquivo() {
    String selecao = getSelecaoButtonGroup(); // Obtém a opção selecionada
    
    // Verifica se alguma opção foi selecionada
    if (selecao == null) {
        JOptionPane.showMessageDialog(this, "Nenhuma opção selecionada!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try (FileWriter writer = new FileWriter("selecao.txt", true)) { // 'true' para adicionar ao invés de sobrescrever
        writer.write(selecao + "\n"); // Adiciona a seleção no arquivo com quebra de linha
        JOptionPane.showMessageDialog(this, "Seleção salva com sucesso!");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Erro ao salvar a seleção!", "Erro", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acompanhamentosBG = new javax.swing.ButtonGroup();
        Lacos = new javax.swing.JRadioButton();
        Anagua = new javax.swing.JRadioButton();
        DataRF = new javax.swing.JTextField();
        Buque = new javax.swing.JRadioButton();
        DataQF = new javax.swing.JTextField();
        Veu = new javax.swing.JRadioButton();
        HorarioF = new javax.swing.JTextField();
        Chapeu = new javax.swing.JRadioButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        DataD = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ObsF = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        NumTrajeF = new javax.swing.JTextField();
        ValorTotal1 = new javax.swing.JLabel();
        VoltarB = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        SalvarB = new javax.swing.JButton();
        ValorF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AdiantamentoF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        RestanteF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        NumTrajeL1 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        comboAtendente = new javax.swing.JComboBox<>();
        NumTrajeL2 = new javax.swing.JLabel();
        EscolaF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        acompanhamentosBG.add(Lacos);
        Lacos.setText("Laços\n");
        Lacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LacosActionPerformed(evt);
            }
        });

        acompanhamentosBG.add(Anagua);
        Anagua.setText("Anágua");
        Anagua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnaguaActionPerformed(evt);
            }
        });

        DataRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataRFActionPerformed(evt);
            }
        });

        acompanhamentosBG.add(Buque);
        Buque.setText("Buquê");
        Buque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuqueActionPerformed(evt);
            }
        });

        DataQF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataQFActionPerformed(evt);
            }
        });

        acompanhamentosBG.add(Veu);
        Veu.setText("Véu\n");
        Veu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeuActionPerformed(evt);
            }
        });

        HorarioF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorarioFActionPerformed(evt);
            }
        });

        acompanhamentosBG.add(Chapeu);
        Chapeu.setText("Chápeu");
        Chapeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChapeuActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("Hórario:");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setText("Observação:");

        DataD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataDActionPerformed(evt);
            }
        });

        ObsF.setColumns(20);
        ObsF.setRows(5);
        jScrollPane2.setViewportView(ObsF);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setText("Data da Quadrilha:");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setText("Data da Devolução:");

        jLabel3.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Edição da Reserva do Traje");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setText("Data da Reserva:");

        NumTrajeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumTrajeFActionPerformed(evt);
            }
        });

        ValorTotal1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ValorTotal1.setText("Valor do Traje:");

        VoltarB.setText("Voltar");
        VoltarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Adiantamento:");

        SalvarB.setText("Salvar");
        SalvarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarBActionPerformed(evt);
            }
        });

        ValorF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("R$");

        AdiantamentoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdiantamentoFActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("R$");

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setText("Restante:");

        RestanteF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestanteFActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("R$");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setText("Acompanhamentos:");

        NumTrajeL1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NumTrajeL1.setText("Número do Traje:");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel39.setText("Atendente:");

        comboAtendente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Luiza", "Júlia", "Apollo" }));
        comboAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAtendenteActionPerformed(evt);
            }
        });

        NumTrajeL2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NumTrajeL2.setText("Escola:");

        EscolaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscolaFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(AdiantamentoF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(230, 230, 230))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel37)
                                            .addGap(88, 88, 88))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel38)
                                            .addGap(31, 31, 31)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Lacos)
                                            .addGap(18, 18, 18)
                                            .addComponent(Anagua))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(18, 18, 18)
                                            .addComponent(RestanteF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(ValorTotal1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(NumTrajeL1)
                                            .addGap(78, 78, 78)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ValorF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NumTrajeF, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buque)
                        .addGap(18, 18, 18)
                        .addComponent(Veu)
                        .addGap(18, 18, 18)
                        .addComponent(Chapeu))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NumTrajeL2)
                        .addGap(89, 89, 89)
                        .addComponent(EscolaF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(18, 18, 18)
                                .addComponent(DataD, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel34))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DataQF, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(HorarioF, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DataRF)))
                            .addComponent(jLabel39))
                        .addComponent(comboAtendente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(VoltarB)
                        .addGap(45, 45, 45)
                        .addComponent(SalvarB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel3)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumTrajeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumTrajeL1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ValorTotal1)
                            .addComponent(ValorF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AdiantamentoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RestanteF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(DataQF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(HorarioF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(DataRF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(DataD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel39)
                        .addComponent(comboAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Lacos)
                        .addComponent(Anagua)
                        .addComponent(Buque)
                        .addComponent(Veu)
                        .addComponent(Chapeu)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EscolaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NumTrajeL2)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VoltarB)
                    .addComponent(SalvarB))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LacosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LacosActionPerformed

    private void AnaguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnaguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnaguaActionPerformed

    private void DataRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataRFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataRFActionPerformed

    private void BuqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuqueActionPerformed

    private void DataQFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataQFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataQFActionPerformed

    private void VeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VeuActionPerformed

    private void HorarioFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorarioFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HorarioFActionPerformed

    private void ChapeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChapeuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChapeuActionPerformed

    private void DataDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataDActionPerformed

    private void NumTrajeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumTrajeFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumTrajeFActionPerformed

    private void VoltarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBActionPerformed
        Menu menu = new Menu(); // Criar uma nova instância da tela Menu
        menu.setVisible(true); // Tornar o Menu visível
        this.dispose();
    }//GEN-LAST:event_VoltarBActionPerformed

    private void SalvarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarBActionPerformed
 try {
    if (NumTrajeF.getText().isEmpty() || ValorF.getText().isEmpty() || AdiantamentoF.getText().isEmpty() ||
        RestanteF.getText().isEmpty() || DataQF.getText().isEmpty() || HorarioF.getText().isEmpty() || DataD.getText().isEmpty()) { 
        
        JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
LocalDate dataQuadrilha = LocalDate.parse(DataQF.getText(), formatter);
LocalDate dataReserva = LocalDate.parse(DataRF.getText(), formatter);
LocalDate dataDevolucao = LocalDate.parse(DataD.getText(), formatter);

    Aluguel aluguel = new Aluguel();

    aluguel.setNumeroTraje(Integer.parseInt(NumTrajeF.getText()));
    aluguel.setValor(Double.parseDouble(ValorF.getText()));
    aluguel.setAdiantamento(Double.parseDouble(AdiantamentoF.getText()));
    aluguel.setRestante(Double.parseDouble(RestanteF.getText()));

    aluguel.setDataQuadrilha(LocalDate.parse(DataQF.getText(), formatter));
    aluguel.setDataReserva(LocalDate.parse(DataRF.getText(), formatter));
    aluguel.setDataDevolucao(LocalDate.parse(DataD.getText(), formatter));

    aluguel.setObservacao(ObsF.getText());
    aluguel.setAcompanhamentos(getSelecaoButtonGroup());

    String atendenteSelecionado = (String) comboAtendente.getSelectedItem();
    aluguel.setAtendente(atendenteSelecionado);

    aluguel.setEscola(EscolaF.getText());

    aluguelDao.salvar(aluguel);
    JOptionPane.showMessageDialog(this, "Aluguel cadastrado com sucesso!");
    salvarSelecaoEmArquivo();
  this.dispose();
         Menu menu = new Menu(); // Criar uma nova instância da tela Menu
        menu.setVisible(true);

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Erro nos valores numéricos!", "Erro", JOptionPane.ERROR_MESSAGE);
} catch (DateTimeParseException e) {
    JOptionPane.showMessageDialog(this, "Formato de data inválido. Use o formato dd/MM/yyyy.", "Erro", JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Erro ao salvar o aluguel: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
}    }//GEN-LAST:event_SalvarBActionPerformed

    private void ValorFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorFActionPerformed

    private void AdiantamentoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdiantamentoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdiantamentoFActionPerformed

    private void RestanteFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestanteFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RestanteFActionPerformed

    private void comboAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAtendenteActionPerformed

    private void EscolaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscolaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscolaFActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarAluguel(aluguelId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdiantamentoF;
    private javax.swing.JRadioButton Anagua;
    private javax.swing.JRadioButton Buque;
    private javax.swing.JRadioButton Chapeu;
    private javax.swing.JTextField DataD;
    private javax.swing.JTextField DataQF;
    private javax.swing.JTextField DataRF;
    private javax.swing.JTextField EscolaF;
    private javax.swing.JTextField HorarioF;
    private javax.swing.JRadioButton Lacos;
    private javax.swing.JTextField NumTrajeF;
    private javax.swing.JLabel NumTrajeL1;
    private javax.swing.JLabel NumTrajeL2;
    private javax.swing.JTextArea ObsF;
    private javax.swing.JTextField RestanteF;
    private javax.swing.JButton SalvarB;
    private javax.swing.JTextField ValorF;
    private javax.swing.JLabel ValorTotal1;
    private javax.swing.JRadioButton Veu;
    private javax.swing.JButton VoltarB;
    private javax.swing.ButtonGroup acompanhamentosBG;
    private javax.swing.JComboBox<String> comboAtendente;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
