/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ateliejunino.telas;

import com.mycompany.ateliejunino.TelaBase;
import com.mycompany.ateliejunino.daos.ClienteDao;
import com.mycompany.ateliejunino.entidades.Cliente;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author User
 */
public class EditarCliente extends TelaBase {
 public EditarCliente(int clienteId) {
        this.clienteId = this.clienteId;

        clienteDao = new ClienteDao();

        initComponents();

        setLocationRelativeTo(null);
    }
    private int clienteId;
    private ClienteDao clienteDao;

    /**
     * Creates new form EditarCliente
     */
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TelefoneF = new javax.swing.JTextField();
        CompF = new javax.swing.JTextField();
        nomeDanF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        CidadeF = new javax.swing.JTextField();
        BairroF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NumF = new javax.swing.JTextField();
        VoltarB = new javax.swing.JButton();
        EstadoF = new javax.swing.JTextField();
        SalvarB = new javax.swing.JButton();
        IdadeF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        IdadeL = new javax.swing.JLabel();
        EscolaF = new javax.swing.JTextField();
        nomeResL = new javax.swing.JLabel();
        TelefoneL = new javax.swing.JLabel();
        nomeDanL = new javax.swing.JLabel();
        RuaF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nomeResF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Número:");

        jLabel1.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Editar Cadastro do Cliente");

        CompF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompFActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Complemento:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Bairro:");

        CidadeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidadeFActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Escola:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Cidade:");

        VoltarB.setText("Voltar");
        VoltarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBActionPerformed(evt);
            }
        });

        SalvarB.setText("Salvar");
        SalvarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarBActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Estado:");

        IdadeL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IdadeL.setText("Idade:");

        EscolaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscolaFActionPerformed(evt);
            }
        });

        nomeResL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nomeResL.setText("Nome (Responsável)");

        TelefoneL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TelefoneL.setText("Telefone:");

        nomeDanL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nomeDanL.setText("Nome (Dançante):");

        RuaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuaFActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Rua:");

        nomeResF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeResFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(434, 434, 434)
                .addComponent(VoltarB)
                .addGap(52, 52, 52)
                .addComponent(SalvarB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TelefoneL)
                    .addComponent(nomeDanL)
                    .addComponent(nomeResL)
                    .addComponent(IdadeL)
                    .addComponent(jLabel17))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IdadeF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeDanF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeResF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TelefoneF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EscolaF, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel8)
                            .addComponent(jLabel18)
                            .addComponent(jLabel25)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EstadoF, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CidadeF)
                            .addComponent(CompF)
                            .addComponent(RuaF)
                            .addComponent(BairroF, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RuaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BairroF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25)))
                            .addComponent(jLabel13))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel14))
                            .addComponent(NumF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(CompF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CidadeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(EstadoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeResF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeResL))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeDanF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeDanL))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IdadeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdadeL))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TelefoneF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TelefoneL))
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EscolaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VoltarB)
                    .addComponent(SalvarB))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CompFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompFActionPerformed

    private void CidadeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidadeFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CidadeFActionPerformed

    private void VoltarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBActionPerformed
        Menu menu = new Menu(); // Criar uma nova instância da tela Menu
        menu.setVisible(true); // Tornar o Menu visível
        this.dispose();
    }//GEN-LAST:event_VoltarBActionPerformed

    private void SalvarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarBActionPerformed
        if (nomeResF.getText().isEmpty() || nomeDanF.getText().isEmpty() || TelefoneF.getText().isEmpty() || EscolaF.getText().isEmpty()|| RuaF.getText().isEmpty() || BairroF.getText().isEmpty()|| NumF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios (Nome Responsável, Nome Dançante, Telefone, Escola, Rua, Bairro e Número", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
       Cliente cliente = new Cliente(
               nomeResF.getText(),        // nomeResponsavel
               nomeDanF.getText(),        // nomeDancante
               Integer.parseInt(IdadeF.getText()), // idade
               RuaF.getText(),            // rua
               NumF.getText(),            // num
               CompF.getText(),          // complemento
               BairroF.getText(),         // bairro
               CidadeF.getText(),         // cidade
               EstadoF.getText(),         // estado
               TelefoneF.getText(),       // telefone
               EscolaF.getText()          // escola
       );
       clienteDao.salvar(cliente);

       JOptionPane.showMessageDialog(null, "Cliente cadastrada com sucesso.");
this.dispose();
         Menu menu = new Menu(); // Criar uma nova instância da tela Menu
        menu.setVisible(true);
          
        }          // TODO add your handling code here:
    }//GEN-LAST:event_SalvarBActionPerformed

    private void EscolaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscolaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscolaFActionPerformed

    private void RuaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RuaFActionPerformed

    private void nomeResFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeResFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeResFActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarCliente(clienteId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroF;
    private javax.swing.JTextField CidadeF;
    private javax.swing.JTextField CompF;
    private javax.swing.JTextField EscolaF;
    private javax.swing.JTextField EstadoF;
    private javax.swing.JTextField IdadeF;
    private javax.swing.JLabel IdadeL;
    private javax.swing.JTextField NumF;
    private javax.swing.JTextField RuaF;
    private javax.swing.JButton SalvarB;
    private javax.swing.JTextField TelefoneF;
    private javax.swing.JLabel TelefoneL;
    private javax.swing.JButton VoltarB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nomeDanF;
    private javax.swing.JLabel nomeDanL;
    private javax.swing.JTextField nomeResF;
    private javax.swing.JLabel nomeResL;
    // End of variables declaration//GEN-END:variables
}
