/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ateliejunino.telas;

import com.mycompany.ateliejunino.TelaBase;
import com.mycompany.ateliejunino.daos.ClienteDao;
import com.mycompany.ateliejunino.entidades.Cliente;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ListaCliente extends TelaBase {

    /**
     * Creates new form ListaCliente
     */
    public ListaCliente() {
        initComponents();
        clienteDao = new ClienteDao();
        load();
        setLocationRelativeTo(null);
    }
 private ClienteDao clienteDao;
    private void load() {
    List<Cliente> cli = clienteDao.pesquisar();

    // Define o modelo da tabela com o número correto de linhas
    DefaultTableModel model = new javax.swing.table.DefaultTableModel(
        new Object[cli.size()][12],
        new String[]{"Id", "Nome Responsavel", "Nome Dancante", "Idade", "Rua", "Número", "Complemento", "Bairro", "Cidade", "Estado", "Telefone", "Escola"}
    );
    
    // Define o modelo da tabela
    ClienteTable.setModel(model);
    
    // Preenche os dados dos clientes na tabela
    for (int i = 0; i < cli.size(); i++) {
        Cliente cliente = cli.get(i);
        model.setValueAt(cliente.getId(), i, 0);
        model.setValueAt(cliente.getnomeResponsavel(), i, 1);
        model.setValueAt(cliente.getnomeDancante(), i, 2);
        model.setValueAt(cliente.getidade(), i, 3);
        model.setValueAt(cliente.getrua(), i, 4);
        model.setValueAt(cliente.getnum(), i, 5);
        model.setValueAt(cliente.getcomplemento(), i, 6);
        model.setValueAt(cliente.getbairro(), i, 7);
        model.setValueAt(cliente.getcidade(), i, 8);
        model.setValueAt(cliente.getestado(), i, 9);
        model.setValueAt(cliente.gettelefone(), i, 10);
        model.setValueAt(cliente.getescola(), i, 11);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ClienteTable = new javax.swing.JTable();
        ExcluirBut1 = new javax.swing.JButton();
        EditarBut1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        VoltaB = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Broadway", 0, 24)); // NOI18N
        jLabel3.setText("Lista");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        ClienteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Responsavel", "Dancante", "Idade", "Rua", "Número", "Complemento", "Bairro", "Cidade", "Estado", "Telefone", "Escola"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ClienteTable);

        ExcluirBut1.setText("Excluir");
        ExcluirBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirBut1ActionPerformed(evt);
            }
        });

        EditarBut1.setText("Editar");
        EditarBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBut1ActionPerformed(evt);
            }
        });

        jButton3.setText("Cadastrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        VoltaB.setText("Voltar");
        VoltaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltaBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(VoltaB)
                        .addGap(59, 59, 59)
                        .addComponent(jButton3)
                        .addGap(72, 72, 72)
                        .addComponent(EditarBut1)
                        .addGap(55, 55, 55)
                        .addComponent(ExcluirBut1)
                        .addGap(189, 189, 189)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(EditarBut1)
                    .addComponent(ExcluirBut1)
                    .addComponent(VoltaB))
                .addGap(29, 29, 29))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel8.setFont(new java.awt.Font("Broadway", 0, 24)); // NOI18N
        jLabel8.setText("Listagem de Clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(396, 396, 396))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltaBActionPerformed
        Menu adm = new Menu();
        adm.setVisible(true);     
         this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_VoltaBActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CadastroCliente cadcon = new CadastroCliente();
        cadcon.setVisible(true); 
         this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void EditarBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBut1ActionPerformed
        if (ClienteTable.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente para editar.");
        } else {
            int clienteId = (int) ClienteTable.getValueAt(ClienteTable.getSelectedRow(), 0);
            new EditarCliente(clienteId).setVisible(true);
            this.dispose();
        } // TODO add your handling code here:
    }//GEN-LAST:event_EditarBut1ActionPerformed

    private void ExcluirBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirBut1ActionPerformed
        if (ClienteTable.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um especialidade para excluir.");
        } else {
            int id = (int) ClienteTable.getValueAt(ClienteTable.getSelectedRow(), 0);
            try {
                clienteDao.excluir(id);
            } catch (SQLException ex) {
                Logger.getLogger(ListaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            load();
        } // TODO add your handling code here:
    }//GEN-LAST:event_ExcluirBut1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ClienteTable;
    private javax.swing.JButton EditarBut1;
    private javax.swing.JButton ExcluirBut1;
    private javax.swing.JButton VoltaB;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
